/home/zhaocg/env/bin/python3.6 main.py --config configs/cnn_with-non-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/cnn_with-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/cnn_without-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/mlp_with-non-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/mlp_with-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/mlp_without-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_bilstm_with-non-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_gru_with-non-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_gru_with-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_lstm_with-non-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_lstm_with-static-w2v.json
/home/zhaocg/env/bin/python3.6 main.py --config configs/rnn_lstm_without-w2v.json